name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # Deploy automatically when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Cache npm dependencies (prevents 429 errors)
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      # 5. Zip source bundle (exclude git files)
      - name: Zip source bundle
        run: zip -r my-app.zip * .[^.]* -x "*.git*" ".github*"

      # 6. Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "CI-CD-demo" # must match EB Application
          environment_name: "CI-CD-demo-env" # must match EB Environment
          version_label: ${{ github.sha }}
          region: "us-east-1" # region of your EB app
          deployment_package: "my-app.zip"
